"""AI SITREP generation: compose the current map state into a prompt and call the
FMAPI chat endpoint. Answers the customer pain point — during TC Jasper people were
sharing printed maps; here the COP writes the brief itself."""

import json

from . import config, dbx, frames, pollers

_SYSTEM = """You are the watchkeeper's drafting assistant in an Australian Defence \
joint operations room, producing a SITREP for a humanitarian aid and disaster relief \
(HADR) operation. Write in Australian military brief style: terse, factual, present \
tense, no speculation beyond an ASSESSMENT section, 24-hour AEST times. Use exactly \
these numbered sections: 1. SITUATION, 2. WEATHER, 3. INFRASTRUCTURE, 4. FORCE \
ELEMENTS, 5. ASSESSMENT. Base every statement strictly on the JSON state provided. \
Classification line first and last: OFFICIAL. Under 400 words."""


def generate(t_index: int | None = None, live: bool = False) -> dict:
    if live:
        state = {
            "mode": "LIVE",
            "road_events": pollers.live_state["roads"],
            "bom_warnings": pollers.live_state["warnings"],
        }
        context_label = "current live feeds"
    else:
        t = t_index if t_index is not None else 100
        state = frames.frame_state(
            t, ["kpis", "track", "warnings", "roads", "readiness", "runways", "flood"]
        )
        spine = frames.timeline[t] if t < len(frames.timeline) else {}
        state["mode"] = "REPLAY — TC JASPER"
        state["as_at"] = {"ts_aest": spine.get("ts_aest"), "phase": spine.get("phase")}
        context_label = f"TC Jasper replay tick {t}"

    text = dbx.chat(
        [
            {"role": "system", "content": _SYSTEM},
            {
                "role": "user",
                "content": f"Generate the SITREP from this {context_label} state:\n"
                + json.dumps(state, default=str)[:24000],
            },
        ]
    )
    return {
        "sitrep": text,
        "generated_by": config.SITREP_ENDPOINT,
        "caveat": "Generated by AI — verify before release.",
    }
